-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.DEMESNE_BASE_MAX_SIZE = 2.0
NDefines.NCharacter.MAX_WARDS_PER_GUARDIAN = 4
NDefines.NCharacter.ASSIGN_ACTION_DAYS = 0
NDefines.NCharacter.MARRIAGE_TIER_DIFF_PRESTIGE_MULT = 10
NDefines.NCharacter.MAX_GENERATED_TRAITS_FOR_HISTORICAL = 5
NDefines.NCharacter.COURT_SIZE_CHILD_PENALTY_THRESHOLD =999
NDefines.NCharacter.MAX_LEADERSHIP_TRAITS = 3
NDefines.NCharacter.FERTILITY_BASE_MULT = 0.60
NDefines.NCharacter.TRIBAL_EMPTY_HOLDING_TAX_MULTIPLIER = 1.0
NDefines.NMilitary.MERCENARY_HIRE_DISTANCE_THRESHOLD = 1200
NDefines.NMilitary.ARMY_MOVEMENT_SPEED = 5
NDefines.NMilitary.NAVY_MOVEMENT_SPEED = 40
NDefines.NAI.RAID_AGGRESSION = 50
NDefines.NAI.DOW_AGGRESSION_FACTOR = 0.25